database:
  hostName: test.com
  port: 3306
  userName: test
  password: test

rcon:
  hostName: test.com
  port: 40336
  password: test

server: Factions

databaseInfos:
  ozelesya:
    dbName: factions
    tableName: ozelesya
    usernameColumn: player
  credit:
    dbName: genel
    tableName: kredi
    usernameColumn: isim
  points:
    dbName: factions
    tableName: unio_points
    usernameColumn: player
  crates:
    dbName: factions
    tableName: kasalar
    usernameColumn: player

settings:
  silentBcmd: true
  silentSendMessage: true

commandInstances:
  "iteminfo": "itemdb"
  "elsat": "sell hand"
  "envsat": "sell inventory"
  "help": "komutlar"
  "kurallar": "rules"
  "kafa": "skull"
  "sandık": "pv"
  "chest": "pv"
  "kasa": "crates"
  "kasalar": "crates"
  "warp market": "market"
  "meslek katıl <text>": "jobs join %arg-2%"
  "meslek ayrıl <text>": "jobs leave %arg-2%"
  "meslek tümündenayrıl": "jobs leaveall"